name: Interpretable-SONAR-Image-Classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow=2.16.1
  - tensorflow-intel=2.16.1
  - tqdm=4.66.4
  - lime=0.2.0.1
  - shap=0.46.0
  - numba=0.60.0
  - numpy=1.26.4
  - opencv-python=4.10.0.84
  - opencv-python-headless=4.10.0.84
  - scikit-image=0.24.0
  - scikit-learn=1.2.2
  - pyparsing=3.1.2
  - cloudpickle=3.0.0
